### ISSUE TITLE
Make cylc task edit-runs rose app aware?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1407]
BoM users have noted that for tasks that are Rose apps, an edit run "only" exposes the complete task job script, not the content of the app configuration.  Of course I have emphasized that this is "not a cylc problem", and in fact not even a Rose problem - it is simply that the rose app is *what the task needs to run* in this case, just like running any model via an existing interface (a front-end script or whatever) that contains much of the job configuration.  **However**, that said, I imagine we could detect direct invocations of rose apps by the suite, and for those tasks open up a temporary copy of the app config in ```rose edit``` and use that, after editing, to run the task?  That would certainly make for the most mind-bogglingly powerful edit runs :grin:   @cylc/core - thoughts?

**Comment by arjclark** [comment]
Nice idea. I think you run into problems as soon as the app to be run uses optional configs though.

I think you're pushing the right line though with it not really being a cylc or Rose problem.

**Comment by matthewrmshin** [comment]
I am not sure if this is a good idea.
* It is quite hard to support correctly because the Rose application configuration may only be installed on the task host.
* It can be tricky edit, because the user will end up having to modify the `rose task-run` command to pick up the edited Rose application configuration from an alternate location.
* I would have imagined that edit run is a facility to fix a contained one-off problem. A quick fix like this should probably be done by editing the `rose task-run` command line with options like `-D [SECTION]KEY=VALUE` or `-O OPT-KEY`.

**Comment by matthewrmshin** [comment]
(Edited my comment above.)

**Comment by dpmatthews** [comment]
After further discussion with @matthewrmshin we don't think this is sensible. An edit run is about changing the job script. Going beyond that would mean completely re-thinking what we mean by job submission.
