### ISSUE TITLE
cylc gui: task output: flexible fetcher

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#1513]
Some batch schedulers (like PBS) hang on to standard output and error streams until the job is finished. This means that a user can't view running task output in `cylc gui` via the normal 'ssh machine cat $HOME/cylc-run/.........../job.out' dialog process. However, there can be custom ways to dig the information out of the scheduler or filesystem.

It would be good if we were able to react to certain machines at certain sites by running a different command instead of 'cat' in `cylc gui`.

**Comment by matthewrmshin** [comment]
(The main complication here is that the current logic is dependent on the task job host only, but really we need a logic that is based on the state of the task + the task job host + the batch system + anything local to the site in order to make a judgement on whether `cat` is sufficient or not.)

Do we need something similar for `cylc cat-log` as well?

**Comment by matthewrmshin** [comment]
Superseded by #1588.
