### ISSUE TITLE
cylc global config: bad configs are silently ignored

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#1554]
If I add something invalid like this to my `~/.cylc/global.rc`:
```
[pyro]
    base port = wellington
```
then my whole user config is silently ignored. The same happens for site configs.

It should probably just fall over with a 'bad user' error.

**Comment by hjoliver** [comment]
Yeah, that's a long-standing problem.  A warning is given in verbose mode:
```
% cylc get-global -i '[suite host self-identification]' -v
Loading site/user config files
Reading file /home/oliverh/.cylc/global.rc
'Illegal option value: [suite host self-identification][method]method = hardwiredx'
WARNING: global config validation failed
```

The reason for this was that a bad site config file should not prevent users from running their suites because they can't do anything about it.  However, the same logic should not apply to the user file.  (Maybe it shouldn't for site either?)
