### ISSUE TITLE
cylc 6.6.0 suite logs can get swarmed by old-client messages

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#1578]
If you run a cylc 6.6.0 suite on a machine with other users running an older version of `cylc scan`, your log can be swarmed by large number of warning messages.

I believe the message is being logged by:
https://github.com/cylc/cylc/blob/master/lib/cylc/network/connection_validator.py#L87

**Comment by hjoliver** [comment]
That's probably due to multiple connection attempts, when the user has a lot of registered suites (each passphrase is tried).  What do you want to do about this - only log rejected connections in debug mode?

**Comment by matthewrmshin** [comment]
I suppose we should at least do that for connection with the old clients, (even though the access denied information may be useful for monitoring purpose).

Are we less likely to see this kind of messages when users scan with the new client?

**Comment by hjoliver** [comment]
New scan clients never get denied, because scan info is freely available by the new connection validation method.

Old scan clients only know the old method.  They first try it with no passphrase (a pointless historical anachronism dating back to when it was possible to get full control with no passphrase) - DENIED; then they try it repeatedly with each passphrase that they can lay hands on - which is DENIED each time until (if) the correct passphrase is tried.

**Comment by hjoliver** [comment]
So yes, an old scan client run by a user with a lot of passphrases registered will generate a lot of DENIED messages.

**Comment by hjoliver** [comment]
I'll take a look on Monday, to see if we can distinguish old scan clients from other types of denied connection.

**Comment by matthewrmshin** [comment]
Thanks!

**Comment by benfitzpatrick** [comment]
I'd like to steal this one if possible (see a80107f). If not, I added a test which we can use.

**Comment by hjoliver** [comment]
Go ahead (and apologies for dropping the ball on this one).
