### ISSUE TITLE
Problem with ssh messaging

### ISSUE THREAD

**Issue by MartinDix** [cylc/cylc#1582]
We use ssh to communicate from the supercomputer back to the server.

With 6.4.1 everything worked fine. In this version `send` in `task_messaging.py` has essentially
```python
        if self.ssh_messaging:
             do something
             if ok:
                return

        self.print_msg( msg )
        self.send_pyro( msg )
```

so the pyro part doesn't get called. We don't have Pyro installed on the supercomputer.

With 6.5.0 (same in 6.6.0), this changed to 
```python
        if self.ssh_messaging and self._send_by_ssh():
            return

        self._send_by_pyro(messages)
```

However the new `_send_by_ssh` function doesn't return a value so the test will always fail and it always falls through to using pyro.

In practice suites still seem to work but give lots of messages like
```
ERROR: task messaging failure.
No module named Pyro.errors
```

**Comment by hjoliver** [comment]
Hi Martin,

Sorry about this - the error must have slipped through our code review
process!   It probably went unnoticed because ssh messaging is not used at
NIWA or Met Office (I think), where all of our automated testing is done.

Anyhow, I'll make sure that we have a test suite to ensure that ssh
messaging remains unbroken in the future (it was originally difficult to do
this at a Pyro site, but I think we could create a test now).

Hilary

**Comment by hjoliver** [comment]
@MartinDix - perhaps you'd like to follow cylc development more closely, keep your clone up to date, and run the test battery at your site?   At the least, before making a new release we could potentially get confirmation that the test battery passes at your site too.

**Comment by hjoliver** [comment]
> Anyhow, I'll make sure that we have a test suite...

(or @matthewrmshin will, I see he's self-assigned this already!)
