### ISSUE TITLE
cylc graph: suite sat in waiting

### ISSUE THREAD

**Issue by kaday** [cylc/cylc#1664]
This bug came in at 6.7.0.
Example suite.rc
```python
[cylc]
  UTC mode = True
[scheduling]
    initial cycle point = 20000101T00Z
    final cycle point   = 20000101T06Z
  [[dependencies]]
      [[[R1]]]
         graph = remove => install_a
      [[[T00]]]
         graph = """
                install_a |\
                foo[-PT12H]:fail => install_b
                foo[-PT12H] => !install_b
                """
       [[[T06]]]
          graph = """
          install_b[-PT6H] => foo => !install_b
          foo:fail => install_b
"""
[runtime]
    [[install_a, install_b, remove]]
        script = true;
    [[foo]]
        script = true;
```
At 6.6.1 or earlier the install_c task appears on the T00 cycle and the suite continues.

From 6.7.0 onwards the install_c task does not run. 
The task is in the poll but `greyed` out as if it needs inserting before it can run and then the suite continue.
The suite then sits in `waiting` and therefore it does not progress.

**Comment by matthewrmshin** [comment]
A quick `git bisect` tells us that #1570 is guilty.

**Comment by hjoliver** [comment]
Is the example suite correct?  It's hard to understand what it's supposed to do, because the `-PT12H` offset doesn't seem to make sense.

> From 6.7.0 onwards the install_c task does not run.
 
I assume you mean `install_b`, since there is no `install_c` in the suite?

If so, the reason for this is that `install_b` immediately suicides in the first cycle:
```
cylc log foo | grep install_b
2015-11-05T23:30:16Z DEBUG - [install_b.20000101T0000Z] -released to the task pool
2015-11-05T23:30:16Z INFO - [install_b.20000101T0000Z] -suiciding
2015-11-05T23:30:16Z DEBUG - [install_b.20000101T0000Z] -forced spawning
2015-11-05T23:30:16Z DEBUG - [install_b.20000101T0000Z] -task proxy removed (suicide)
2015-11-05T23:30:17Z DEBUG - [install_b.20000101T0600Z] -released to the task pool
```
To the extent that ignoring pre-initial triggers is the right thing to do #1603, this is the correct behaviour IMO, because in the first cycle this:
```
graph = foo[-PT12H] => !install_b
```
becomes this:
```
graph = !install_b
```

So, it seems to me this is *a suite design issue*, not a cylc bug :grimacing:

**Comment by kaday** [comment]
I agree and I will add a comment in a minute, basically it should never have worked!

**Comment by kaday** [comment]
We agree this is definitely a suite design issue.
