### ISSUE TITLE
gcylc: polling no longer feeding back to gui

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1690]
It has been noted that gcylc is no longer feeding back information about polling to the gui.

Examples include:
Polling a specific task:
 * Previously (6.4.1): this would result in an entry in the message column to the effect of "poll succeeded ..."
 * Now: nothing. Not clear to users that anything has actually happened without going into the logs

Polling whole suite:
 * Previously (6.4.1) the window that appears contained the line "Command Queued" confirming that it was queueing up the poll operation
 * Now: nothing. Blank seemingly pointless window appears. Again, not clear to users what is going on.

**Comment by hjoliver** [comment]
I figured this was a deliberate change by Matt, to stop treating poll results as anything special (??) - but I've been meaning to query this myself.  If you do a manual poll, it is good to get confirmation that it actually happened.

**Comment by hjoliver** [comment]
Re "blank seemingly pointless window" - see #1671

**Comment by matthewrmshin** [comment]
For individual task poll/kill, we are reporting poll/kill failure, but not success for some reason. I think we can easily put it back in. (I have probably forgotten to put it back!)

For the poll all operation, I think we have lost the *Command Queued* message since the network and authentication re-factor.
