### ISSUE TITLE
cylc gcylc: ports file error message incorrect

### ISSUE THREAD

**Issue by kaday** [cylc/cylc#1697]
This still produces an error message 
`ERROR, remote port file not found.`
in the gcylc GUI when the suite stops normally:
https://github.com/cylc/cylc/pull/1395#issuecomment-100752292

**Comment by hjoliver** [comment]
This message is emitted when gcylc is connected to a suite running on a remote host.   I hadn't noticed this because locally I almost always run gcylc on the suite host, in which case the equivalent message is a little more friendly:

Local suite:
   ```Port file not found - suite not running?```

Remote suite:
   ```ERROR, remote port file not found.```

For local or remote suites, the message does not appear if the suite is told to shut down by the GUI instance in question (because then the GUI "knows" about the impending shutdown).  You'll still see the message in other GUI instances, or if the suite shuts down of its own accord.

In the first instance, I'll change the remote suite message to the nicer/clearer local message, for today's release of 6.7.4.  Then we can potentially go further for the next release.   But IMO it should not be removed entirely as it informs the user of exactly why the GUI cannot connect to its target suite: there is no port file that says what port to connect to.  That can be because of an error (port file erroneously deleted) or just because the suite is not actually running.  The question is, can we reliably distinguish the two cases?

**Comment by arjclark** [comment]
> The question is, can we reliably distinguish the two cases?

The only hint we currently have is that the suite logs contain a "shutting down" message - possibly that could be scraped or something but I don't think that's reliable or efficient. A potentially more elegant idea would be to set a flag in the suite daemon that is readable by the communication interface (like the task states) along the lines of "shutting_down_cleanly=True|False". So if a shutdown is in progress the gui could (hopefully) pick up on that.

**Comment by hjoliver** [comment]
@arjclark and @kaday - from testing, it seems I was wrong about this:
> the message does not appear if the suite is told to shut down by the GUI instance in question, because then the GUI "knows" about the impending shutdown. You'll still see the message in other GUI instances, or if the suite shuts down of its own accord.

Actually, the scheduler does tell the suite state summary object, and hence gcylc, about an impending shutdown,   So if you call `cylc stop` on a suite, all GUI instances connected to it will detect this and will not pop up the warning dialog when the connection is lost post shutdown.  The problem seems to be just that for a normal shutdown the state goes from 'running' to 'stopping' and then actual shutdown too fast, i.e. there's no final update to the state summary object.
