### ISSUE TITLE
Tweaking `cylc monitor` or `cylc scan` for easier use

### ISSUE THREAD

**Issue by chanwilson** [cylc/cylc#1752]
Although it's a minor thing, it'd be nice if the output from a `cylc scan` could be cut-n-pasted and fed directly to a `cylc monitor`, instead of needing to transpose and --option-ize arguments...

Eg, enable usage like 

```
cylc monitor `cylc scan --host localhost --all | grep LNOx` 
```

**Comment by hjoliver** [comment]
Chan,

I'm not sure I entirely understand what you're suggesting.  If you know a
suite's name and host, you can just give that directly to "cylc monitor",
but if it might be any one of several suites with names that match a
pattern, then you might find more than one suite running and the monitor
command will fail.  Or do you know the suite's name, but not which host it
is running on?  Either way, your scan command line looks wrong.  By default
"cylc scan" will scan localhost, or a list of hosts set in the global
config file.  To scan other hosts, list them as command line arguments, not
options: "cylc scan HOST1 HOST2 ..."

Regards,
Hilary

**Comment by chanwilson** [comment]
Hilary,

OK, better usage example:

`cylc scan` output is like so:
```
fre.awg_ulm_201505.c96L48_am4g7_fullchem_nitrate_cloud_LNOx.multiple.19810101-20100101 Joe.User@localhost:7770
```
`cylc monitor` needs the user@host:port split apart into arguments, it can't be fed (cut-n-paste or backticks ) directly.  Annoying.  Minor glob of perl workaround (replace `print` with `exec` in use) to transmorgify things:

```
cylc scan --host an006 --all --pyro-timeout=3 | grep LNOx | perl -nae '($u,$h,$p) = $F[1] =~ /(.*?)@(.*?):(\d+)/; print qq{cylc monitor --user $u --host $h --port $p $F[0]\n}'
cylc monitor --user Joe.User --host localhost --port 7770 fre.awg_ulm_201505.c96L48_am4g7_fullchem_nitrate_cloud_LNOx.multiple.19810101-20100101
```

make more sense now? :grin:

**Comment by hjoliver** [comment]
Chan,

Thanks for clarifying.

OK, it's not an unreasonable request given that users often want to monitor
suites found by port scanning.   I'll put post a new issue to get "cylc
monitor" to take the minimal scan output as input (suite-name user@host
:port).

Note that if use the GUI you can click on suites in "cylc gscan" to open
"cylc gui" instances (although gscan doesn't yet show other user's suite
like scan does).

Note also, your use of the '--host' option with "cylc scan" probably isn't
doing anything.  That option normally tells cylc clients which host a
target suite is on, but cylc scan is different in that it connects to
multiple suites on multiple hosts that are specified as command line
arguments or listed in global config.   So "--host" is not used by "cylc
scan" unless "--use-ssh" is specified as well, which results in the scan
command being invoked on the remote host instead of locally.   These
options are added automatically to many commands, along with the help
information, and in this case at least the command help is not very helpful
- so I'll put up an issue to fix this too!

Hilary

**Comment by hjoliver** [comment]
So: this would be the CLI analogue of clicking on a suite in gscan to open a gcylc instance.

**Comment by oliver-sanders** [comment]
Would something like this be acceptable?

https://github.com/cylc/cylc/compare/master...oliver-sanders:1752.cylc-monitor-gscan-copy-paste

**Comment by hjoliver** [comment]
Yeah that's good, thanks - put up a PR.  @chanwilson - if you're out there, do you want to take a look?  On Oliver's branch I can do this:
```
cylc monitor $(cylc scan host1 | grep foo)
```

**Comment by chanwilson** [comment]
Looks dandy! thanks.
