### ISSUE TITLE
open '> cylc monitor [suite-ID]' for all running Cylc suites?

### ISSUE THREAD

**Issue by jonnyhtw** [cylc/cylc#1764]
Hi there. 

I can successfully run 'cylc monitor [suite-ID]' but I have 3 suites running and would ideally like to be able to run one 'monitor' command which opens multiple instances of '> cylc monitor', perhaps using the multiplexing capabilities of 'screen'?

Does the functionality exist to do this and if not, would others find this useful? 

I am happy to contribute to this if others think that this may be of use but I thought it best to ask first.

Using Rose/Cylc there is the option use '> rose suite-gcontrol --all' but this potentially opens up many X windows which I don't want.

This is clearly not an urgent issue but this would be useful in the long run I think.

Thank you

Jonny

**Comment by hjoliver** [comment]
Not currently available, but I agree it might be useful.  

#1752 is related

**Comment by hjoliver** [comment]
Had a think about this: opening a monitor on single scan output will be easy once #1752 is done.  Then:
 * it may  be best for us to simply document how users can open multiple monitors at once using screen, as per http://superuser.com/questions/386059/how-can-i-start-multiple-screen-sessions-automatically.  
 * having built-in support that relies on screen may not be desirable, because:
   * it introduces a dependence on another 3rd party package
   * dealing with result of the command requires knowing how to use screen

**Comment by hjoliver** [comment]
@jonnyhtw - due to (many!) competing priorities and the reasoning outlined in my previous comment above, I've decided to close this.  It might well be useful for those running a small number of suites *and* who know how to use `screen`, but for others it could start a large number of monitor processes that are essentially invisible to them, so maybe shouldn't be a built-in cylc feature.  As suggested above, however, it will be easy for screen experts to do at will once #1752 is in (and we could even document the command line to do it at that point).

**Comment by jonnyhtw** [comment]
Thanks @hjoliver and apologies for not seeing it sooner. I have subsequently discovered `cylc gscan` which basically has all the functionality that I wanted anyway.

Cheers
