### ISSUE TITLE
Automated performance tests?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1772]
It would be good to have some automated tests to help us avoid taking big steps backwards in terms of performance - e.g. memory use, CPU use, or elapsed run time for certain extremely active large suites like `dev/suites/busy`.  Such tests would require comparing results with previous results, rather than against some absolute mark and would likely be platform specific too (and even dependent on other load on the host at the time) so this might not be easy.

**Comment by hjoliver** [comment]
One idea, after a quick think on this:

Performance tests could simultaneously run the test at the latest checked out version and at some previous version (e.g. previous release) so that they both run under the same load conditions on the same host.   This should probably not be done as part of the normal test battery.

**Comment by arjclark** [comment]
Upvote on this from me - have just accidentally discovered a massive increase in validation time for certain suites as a result of a change on master that wasn't in the last release (currently with @matthewrmshin for investigation) which could've caused a real headache here.

Wonder if we should go for something configurable for comparing against rather than just the last release (or use last release as default and support overriding with a commit number).

**Comment by hjoliver** [comment]
Yeah, agreed on the configurability.

**Comment by hjoliver** [comment]
[meeting]
  * quite important, @benfitzpatrick to consider this soon

**Comment by arjclark** [comment]
@oliver-sanders - I believe this ties in with the work you're going to be doing for the December milestone
