### ISSUE TITLE
cylc unregister: running suites can be unregistered

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc#1796]
It is currently possible to unregister a running suite with `cylc unregister`, the suite remains visible to `cylc scan` but `cylc shutdown` yields `[client-connect] DENIED (privilege 'state-totals' < 'shutdown')`.

**Comment by matthewrmshin** [comment]
Yes, you will no longer be able to contact the suite because `cylc unregister` removes the `passphrase` file. It is possible, I suppose, to disallow `cylc unregister` if a port file exists. (However, there is nothing we can do if the user manually deletes the `passphrase` file or the register file under `~/cylc/REGDB/`.

**Comment by matthewrmshin** [comment]
See also #1729, #1774, metomi/rose#1824, metomi/rose#1866 for recent (and proposed) changes in passphrase and port file discovery logic.

**Comment by arjclark** [comment]
> It is possible, I suppose, to disallow cylc unregister if a port file exists

This is pretty much what should be happening here regardless and is currently possible to do when you have suites of the form `foo` and `foobar` where unregistering `foo` will result in unregistering a running `foobar` suite because cylc unreg uses a regex and mismatches it.

**Comment by hjoliver** [comment]
> foo will result in unregistering a running foobar suite because cylc unreg uses a regex and matches it against foobar

 We should fix this - my fault I think - the supplied suite name should be an exact match or have explicit wildcards, not a substring (with assumed wildcards)
