### ISSUE TITLE
validation slowed down by vizualisation settings

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1911]
Narrowed down the slow validation (3 minutes) problem to a setting in the suite visualization.

If the visualization in the (hourly cycling) suite concerned is this:

```
[visualization]
    initial cycle point = 20150112T03
    final cycle point = 20150305T18
```

it takes the bulk of 3 minutes to validate.

If I change it to this:

```
[visualization]
    initial cycle point = 20150112T03
    final cycle point = +P1D
```

it only takes 7 seconds.

Something odd's going on here...

**Comment by hjoliver** [comment]
(I think this one was mentioned in passing during our meetings in Exeter?).  Your suite must be quite large as a small one with those settings validates quickly.  However, even a small suite can be made to validate slowly with a visualization final point that is sufficiently far removed from the initial point.

Arguably this is "user error" because those settings determine the extent of the plotted graph, and in this case they're asking cylc to generate a ridiculously large graph.  Whether or not we should generate the full extent of the graph during validation is another matter - perhaps not, but that just postpones the problem until the user tries to visualize the suite.   I suppose we could have a maximum number of allowed graph points, say 100 or so?

**Comment by arjclark** [comment]
Suite concerned was a LAM with ensemble type things in it.

> Arguably this is "user error" because those settings determine the extent of the plotted graph, and in this case they're asking cylc to generate a ridiculously large graph. Whether or not we should generate the full extent of the graph during validation is another matter - perhaps not, but that just postpones the problem until the user tries to visualize the suite. 

Disagree, I think this is more of an unintentional consequence where visualization settings are impacting on validation. I think if they want to visualize the suite out to some suitably distant point then that's their problem if its slow (and would be expected). During validation, however, these visualization settings should be irrelevant beyond "are they valid". When I plot it it may be useful to show multiple cycles but while I'm trying to validate a suite as part of start up then only the dependencies and runtime section should really impact on this.

**Comment by hjoliver** [comment]
@arjclark - fair point, I generally agree.   However, it's possible that we're generating the graph in order to check some aspect of graph validity that can't easily be determined by merely passing the graph strings (e.g. are all conditional trigger expressions valid?) ... I can't recall offhand though, will have to look at the code.
