### ISSUE TITLE
Tasks which are held lose their held status on a restart

### ISSUE THREAD

**Issue by malcolmbrooks** [cylc/cylc#2050]
In the process of debugging suite tasks it can be very useful to hold a suite while an individual task is rerun multiple times.

Sometimes the task can be set up so that it succeeds, but not actually run as required. For instance, changing a forecast task so that it ends on the timestep before it fails means that diagnostic fields can be written out for in depth analysis in order to track down numerical instabilities or bugs. In this instance it is vital to hold the suite and run only the required tasks.

This process is painfully slow, especially if the failure occurs in a large job that takes a lot of compute resource. This sort of task can very easily take multiple weeks, so the suite will likely timeout over the weekend, and at the moment when a suite is restarted on a Monday morning it will immediately try and run all of the previously held tasks.

Because of this, tasks which are held need to remain held when the suite is restarted.

**Comment by hjoliver** [comment]
Agreed.

The reason for the current behaviour is that suite shutdown is implemented by holding all waiting tasks, and then shutting down once all tasks are held or succeeded.  These held tasks are released automatically (to 'waiting') on restart, because (normally at least!) the user did not actually ask them to be held.

However, as noted in #620, setting tasks to held is unnecessary - it dates back to to the days when we did not have the ability to suspend job submission other than by setting task state to held.  @matthewrmshin - this might be a good excuse to up the priority of #620.  Once that's solved we no longer need to treat the held state as special on restart.

**Comment by matthewrmshin** [comment]
In which case, there are several parts to fix here:

1. #620 I think the easiest way is to ensure that tasks beyond the final cycle point are not released from the run ahead pool to the main pool.
2. The suite DB should store:
  * The flag that indicates when the suite is held.
    * `cylc restart --hold` should be automatic if suite was held previously.
  * The swapped out task status while a task is held.
  * The (submission) retry state of each task - so a task does not retry prematurely on restart.
  * See also #864 and #1032.
3. Restart should load the settings stored above, handling held tasks correctly.

I'll tackle this issue as soon as #2004 is merged. Otherwise, it is going to be a messy merge.

**Comment by arjclark** [comment]
2. May also need to record tasks that have been manually held so they aren't reset on restart either (where you manually set a task state to held so as to checkpoint things).

**Comment by matthewrmshin** [comment]
Having another thought... I cannot see why we need to store a flag for suite hold - given that full suite hold/release is currently implemented by holding/releasing all tasks.
