### ISSUE TITLE
Dump environment to stderr on job fail?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2150]
If an error is trapped by the job script, or when running in debug mode, we could this before exiting.
```
env 1>&2
```
@cylc/core - any objections to this?  The environment might occasionally have useful diagnostic info...

**Comment by matthewrmshin** [comment]
No objection, can be done as part of #2141 or as a follow up. However, I'd use `printenv`, for correctness.

From `man printenv` and `man env`:
* printenv - print all or part of environment
* env - run a program in a modified environment

**Comment by dpmatthews** [comment]
I'm not a fan of this for normal use. At the moment, if you have a well written task which fails then hopefully you can take a look in job.err and expect to find a clear error message telling you what happened. With this change that message would then be followed by lots of extra output which would only be of very occasional use (probably more relevant when debugging a new suite rather than more generally).

**Comment by arjclark** [comment]
I wouldn't want it in the main .out/.err files (pretty much for the reasons @dpmatthews gives above) but I don't think I'd massively object if it was in a .env file or something to that extent.

**Comment by matthewrmshin** [comment]
I suppose we don't have to have this built-in. If users are worried about the environment, it should be relatively straightforward to stick a `printenv` command in `pre-script` or something? Or do we need a customisable on-error-script that gets called as part of the error trap?

**Comment by hjoliver** [comment]
Good points all.  BTW this was a suggestion from someone at BoM.  

I like the idea of a custom on-error-script that gets called by the error trap.  I think output from that should probably go to stderr, but if you put `printenv` in it then ... you get what you asked for.
