### ISSUE TITLE
custom task fail messages for event handling

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2274]
Currently task failure is defined by trapping early/abnormal exit from the job script, and no custom message can be passed back to the suite daemon (just "failed").

In cases where the job script deliberately aborts on detecting a problem it would be useful to send an explanatory message back to be logged and passed to the task-failed event handler.

This is not really needed if you use the built-in email event handler and have direct access to job logs via Rose Bush, but it would be useful where event handlers are used to send alerts further afield, where job logs are not easily viewable.

**Comment by hjoliver** [comment]
@cylc/core - thoughts one this?

Presumably we'd need some way to send the custom task failed message and then immediately abort after unsetting the error trap to avoid a double failed message.  (actually we might be able to do this manually already, with the right scripting...)

**Comment by matthewrmshin** [comment]
Some thoughts:

We currently have a warning task event handler which is triggered when a warning message is received, but there is no task event handler for a critical message. (I guess that's because the only critical message is always the failed message or the signal message accompanying a failure.)

The job script currently sends 2 messages (in a single command) to notify a failure, one message for the signal received and the other message for the actual word `failed`.

We can enhance the [cylc__job__trap_err](https://github.com/cylc/cylc/blob/7.3.0/lib/cylc/job.sh#L162) shell function to take extra arguments for any custom messages. The shell function would already unset all traps and exit with return code 1. The extra arguments can be added to the command that sends the failure messages.

Or do you want to have custom messages configurable at the `suite.rc` level?

(As a matter of interest, who is the target audience for this? If you have no good access to the job logs, then it is also unlikely that you will be unable to investigate or fix any issues...)

**Comment by hjoliver** [comment]
@matthewrmshin - 

My initial suggestion was to send a custom WARNING message before aborting, but that doesn't play well with automatic retries: the warning handler - to alert of impending failure in this case - will be invoked in every try, but the actual failure (as far as Cylc is concerned) - and the failed event handler - will not hit till the last try. 

No, I wasn't thinking of custom error messages configurable in the `suite.rc`, just the job script.

So I think we should:
 * enhance `cylc__job__trap_err` as you suggest (I guess the custom message would replace "job received signal..." in this case)
 * add 'critical handler' functionality - it doesn't really make sense that we only have warning handler, given that users can send arbitrary CRITICAL priority messages.

(The target audience is interested in 24/7 operators getting as much information about failures as possible to a dashboard that sees more than just Cylc suites.  They will pass the information on to 2nd level support, if necessary, who see the job logs and can fix the problem).
