### ISSUE TITLE
cylc graph: excluded tasks appearing

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc#2280]
`cylc graph` is not compatible with exclusions (#1928, #2244, #2258).

E.g. For this suite...
```
[scheduling]
    initial cycle point = 20000101T00Z
    [[dependencies]]
        [[[P1D ! 20000103]]]
            graph = task[-P1D] => task
```
... `cylc graph` will display:
```
task.20000101T00Z
task.20000102T00Z
task.20000103T00Z  # Erroneous!
task.20000104T00Z
...
```

**Comment by hjoliver** [comment]
I'm not sure if this is a bug or not.  It might due to inconsistent use of time zone (Z or not) in your example?  If I specify UTC mode, it works fine:

```
 [cylc]
    UTC mode = True
[scheduling]
    initial cycle point = 20000101T00Z
    [[dependencies]]
        [[[P1D ! 20000103]]]
            graph = task[-P1D] => task
[visualization]
   number of cycle points = 5
```
Result:
![foo](https://cloud.githubusercontent.com/assets/2362137/26025062/e7be8126-3822-11e7-8005-56a423b99b47.png)

This graph is correct - 20000103T0000Z is excluded from the cycling sequence, but the graph still defines it as a prerequisite of the 04T0000Z task.

**Comment by oliver-sanders** [comment]
> This graph is correct - 20000103T0000Z is excluded from the cycling sequence, but the graph config still defines it as a prerequisite of the 04T0000Z task.

OK, a little confusing perhaps. For the future it would be nice to mark the pre-requisite as a "ghost node" as we do in `gcylc` to make it clear that it is inferred rather than defined in the graphing.

**Comment by hjoliver** [comment]
We should definitely not remove these nodes from the graph, because they explain why such a suite will stall if you run it - i.e. the graph defines dependence on a task that is not instantiated according to our "no implicit cycling" rule.

> it would be nice to mark the pre-requisite as a "ghost node"

However, this is a good idea!
