### ISSUE TITLE
bug while reloading?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#2309]
Reported at 6.11.1 - need to check at latest version:

>I’ve notice that if a suite is reloading its definition while a task completes the succeeded return code
doesn’t get processed/caught and the task stays in the running state within the suite.
(even though it has
cylc (scheduler - 2017-05-26T00:29:04Z): succeeded at 2017-05-26T00:29:04Z
JOB SCRIPT EXITING (TASK SUCCEEDED)
in the log)

**Comment by matthewrmshin** [comment]
I am unable to repeat on master. I have put in sleeps and delays to ensure that the succeeded message comes in while task pool is reloading the task definition. In all cases, the message gets processed correctly following the reload. I guess the user has given us the output from `job.out`. In order to investigate further, I think it would be more interesting to see the suite log to get a better picture of the sequence of events.

**Comment by matthewrmshin** [comment]
@hjoliver Unless you are able to repeat this or is able to get hold of more information, I suggest we close this.

**Comment by hjoliver** [comment]
@matthewrmshin - thanks for testing this. I can't reproduce it either, tested at 6.11.1 and 6.11.2.  Closing for now, can reopen later if nec.
