### ISSUE TITLE
CYLC_VERSION='7.5.0' WARNING: server has no HTTPS support

### ISSUE THREAD

**Issue by dch1fc** [cylc/cylc#2451]
Hi all,
I am using the following version of Rose and Cylc

CYLC_VERSION='7.5.0'
ROSE_VERSION='2017.10.0'

I am getting this warning message:
WARNING: server has no HTTPS support, falling back to HTTP: [Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol.

This warning message disappeared when i changed the communication method to HTTP
Any thoughts this 

Thanks
Fati

**Comment by matthewrmshin** [comment]
Hi @dch1fc,
* Are you sure you are using cylc-7.5.0?
* The issue should have been fixed by #2355.
* Your suite was started in a Python environment that was unable to import the `OpenSSL` module. This should only be possible before cylc-7.5.0. In cylc-7.5.0, if you attempt to do this, suite start up would fail unless you have explicitly configured communication method to be `http`.
* The error message you have given suggested that you are running a pre-cylc-7.5.0 client. The *fallback* mechanism and this warning message do not exist in cylc-7.5.0.

Please feel free to reopen this issue if you think I am wrong!
