### ISSUE TITLE
Feature request: task names which are just the parameter

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc#2454]
I have only tested this in 7.4 as it is what I have available to me at the moment, but is there any chance of having it so that a parameterized task can be the whole task or family name, instead of needing to have another string attached to it?

Cutdown e.g.
```python
[cylc]
    [[parameters]]
        r = 0..2
[runtime]
    [[<r>]]
```

A properly done suite.rc for the above leads to 
```python
NoneType' object has no attribute 'groups'
```
**** If this idea doesn't gain favour or is put on the backburner for the future, it would be handy to have a more meaningful error message than the above - scan for a pattern like `[<.+>]` and then tell people its a bad line and you cannot have a parameter as the full task/family name and abort? I'm not sure how the validation works to provide more ideas than that

If I make the task `[[a<r>]]` however I get: 
```python
Valid for cylc-7.4.0
```

**Comment by hjoliver** [comment]
@ColemanTom - fair point.  An integer task name isn't a great idea when you consider task instances with the cycle point attached (particular if it's an integer cycle point), but for string-valued parameters - `r = cat, dog, fish` - your suggestion makes sense.   And our unhandled exception really makes this a bug fix rather than a feature request...

**Comment by hjoliver** [comment]
(will promote to next release if we can do this quickly)
