### ISSUE TITLE
Ability to add your own color scheme

### ISSUE THREAD

**Issue by mareecarroll** [cylc/cylc#2508]
In gscan 

View > Theme

Ability to load your own color scheme here

e.g if you are used to other colours or you get confused between colours

**Comment by hjoliver** [comment]
@mareecarroll - gscan will use the theme that you have selected for in your gcylc.rc, which can be a custom theme, and custom themes will appear in the gscan View -> Theme list.  (Note that the theme is picked up from `gcylc.rc` not `gscan.rc` - because there's no good reason to use a different state theme for the two GUIs).

I'll close this as invalid, but feel free to re-open (or comment on the closed issue) if this does not work for you as described.
