### ISSUE TITLE
Add information about prerequisites to task environment

### ISSUE THREAD

**Issue by TomekTrzeciak** [cylc/cylc#2555]
I think it would be really useful to have task prerequisites available as a task environment variable. For example, this could used to work out task inputs based on its dependencies. I guess at the very minimum a list of `<task-id>:<state>` values would do, but for more complicated trigger conditions one might also be interested to know the actual states of the prerequisite tasks that fulfilled the trigger expression to work out which of them are relevant.

**Comment by matthewrmshin** [comment]
Hi @TomekTrzeciak With #2507, (instead of introducing extra stuffs to the job script), do you think it will be relatively straightforward to use something like `cylc show --json "${CYLC_SUITE_NAME}" "${CYLC_TASK_ID}"` to determine what the prerequisites are? Or do you want something more sophisticated?

**Comment by TomekTrzeciak** [comment]
I guess `cylc show --json` would be ok (and probably good have in any case), although for shell scripting json is not particularly friendly - reading environment seems easier.

**Comment by hjoliver** [comment]
`cylc show` has a "raw" (plain text) format too, that is probably better for shell scripting.
