### ISSUE TITLE
Possible error in tutorial documentation, Jinja2 section

### ISSUE THREAD

**Issue by andymoorhouse** [cylc/cylc#2953]
In the Jinja2 section of the Tutorial here https://cylc.github.io/cylc/doc/built-sphinx/tutorial.html#jinja2 the reader is given two `cylc view` commands to see the different results depending on the value of the `MULTI` variable. The two commands are currently identical, i.e. they both say:

`cylc view --jinja2 --stdout tut/oneoff/jinja2`

If the intention is that the reader edits the `suite.rc` file and sets the `MULTI` value as appropriate before running the cylc view command then that should be explicitly stated. However, the intention might be that you supply the MULTI variable as a flag to the cylc view command instead, in which case the two example commands should be corrected appropriately.

**Comment by sadielbartholomew** [comment]
I have just looked into this as I suspected it may have been a mistake arising from the recent conversion from LaTeX to Sphinx where the same command might have been copied wrongly, but having checked this content before & after that PR it was not, as the commands were identical originally.

I think the intention is clear enough, but that is just my view, & I suppose it would be nice to set it explicitly via command if for any reason to advertise the particular option to ``cylc view``. I will put in a PR to amend one command in light of this, since it is a small, quick fix.

**Comment by sadielbartholomew** [comment]
... also it seems silly to set ``MULTI`` to False & then reset it back to its original value, instead of ``view``ing in the other order.

**Comment by sadielbartholomew** [comment]
Fixing this actually took me (longer than expected since I went) down a bit of a "rabbit hole"! Applying a ``--set=MULTI=False``/``="False"`` option to the command in question actually had no effect, so that I initially thought the ``--set`` option to ``cylc view`` did not work & went to investigate that, & also to verify it via another example suite in the docs in which I found a number of other errors! Actually, the redundancy of the additional option stemming from passed-in Jinja2 variables being interpreted as strings, therefore ``False`` being non-empty & considered "truthy". So there was an error after all.

Phew! PR going up now.
