### ISSUE TITLE
EMPTY WORK DIRECTO REMOVE assumes $HOME set

### ISSUE THREAD

**Issue by m214089** [cylc/cylc#931]
Hi HIlary,
there is a problem with the following construct:
```
# EMPTY WORK DIRECTORY REMOVE:
cd
rmdir $CYLC_TASK_WORK_DIR 2>/dev/null || true
```
cd without argument tries to go back to the home directory. On, at least, one of our compute clusters HOME is not available on the compute nodes so this creates an error.
I think, it is saver to return to $CYLC_SUITE_DEF_PATH, which must be available.
Cheerio,
Luis

**Comment by hjoliver** [comment]
@m214089 - apologies, this issue slipped my notice for a while. Did you come to any conclusions on the best way forward here?

**Comment by matthewrmshin** [comment]
I guess this is related to #907? In which case, the problem should be solved by #1166:

> Job file now sources `$HOME/.cylc/job-init-env.sh`, `$CYLC_DIR/conf/job-init-env.sh` or `$CYLC_DIR/conf/job-init-env-default.sh` on initialisation. This allows the job environment to be globally configured for site or user.

E.g. If you have added a `$CYLC_DIR/conf/job-init-env.sh` file in your job host, the job will source the content of this file instead of `/etc/profile` and `~/.profile`. This should hopefully be enough to allow you to set up the environment for cylc and other essential commands.

(I may not have documented the functionality properly, however.)

**Comment by matthewrmshin** [comment]
> (I may not have documented the functionality properly, however.)

Usage of `$CYLC_DIR/conf/job-init-env.sh` documented in #1424.

**Comment by matthewrmshin** [comment]
@m214089 please re-open if this is still an issue.
